const categories = [
  { title: "Actions pt. 1", name: "actions_1" },
  { title: "Actions pt. 2", name: "actions_2" },
  { title: "Animals pt. 1", name: "animals_1" },
  { title: "Animals pt. 2", name: "animals_2" },
  { title: "Clothes", name: "clothes" },
  { title: "Emotions", name: "emotions" },
  { title: "Food", name: "food" },
  { title: "House", name: "house" }
];

const words = [
  [
    {
      word: "cry",
      translation: "плакать",
      imageSrc: "./src/img/word_card_img/cry.jpg",
      audio: "./src/audio/word_card_audio/cry.mp3",
    },
    {
      word: "dance",
      translation: "танцевать",
      imageSrc: "./src/img/word_card_img/dance.jpg",
      audio: "./src/audio/word_card_audio/dance.mp3",
    },
    {
      word: "dive",
      translation: "нырять",
      imageSrc: "./src/img/word_card_img/dive.jpg",
      audio: "./src/audio/word_card_audio/dive.mp3",
    },
    {
      word: "draw",
      translation: "рисовать",
      imageSrc: "./src/img/word_card_img/draw.jpg",
      audio: "./src/audio/word_card_audio/draw.mp3",
    },
    {
      word: "fish",
      translation: "ловить рыбу",
      imageSrc: "./src/img/word_card_img/fish.jpg",
      audio: "./src/audio/word_card_audio/fish.mp3",
    },
    {
      word: "fly",
      translation: "летать",
      imageSrc: "./src/img/word_card_img/fly.jpg",
      audio: "./src/audio/word_card_audio/fly.mp3",
    },
    {
      word: "hug",
      translation: "обнимать",
      imageSrc: "./src/img/word_card_img/hug.jpg",
      audio: "./src/audio/word_card_audio/hug.mp3",
    },
    {
      word: "jump",
      translation: "прыгать",
      imageSrc: "./src/img/word_card_img/jump.jpg",
      audio: "./src/audio/word_card_audio/jump.mp3",
    },
  ],
  [
    {
      word: "open",
      translation: "открывать",
      imageSrc: "./src/img/word_card_img/open.jpg",
      audio: "./src/audio/word_card_audio/open.mp3",
    },
    {
      word: "play",
      translation: "играть",
      imageSrc: "./src/img/word_card_img/play.jpg",
      audio: "./src/audio/word_card_audio/play.mp3",
    },
    {
      word: "point",
      translation: "указывать",
      imageSrc: "./src/img/word_card_img/point.jpg",
      audio: "./src/audio/word_card_audio/point.mp3",
    },
    {
      word: "ride",
      translation: "ездить",
      imageSrc: "./src/img/word_card_img/ride.jpg",
      audio: "./src/audio/word_card_audio/ride.mp3",
    },
    {
      word: "run",
      translation: "бегать",
      imageSrc: "./src/img/word_card_img/run.jpg",
      audio: "./src/audio/word_card_audio/run.mp3",
    },
    {
      word: "sing",
      translation: "петь",
      imageSrc: "./src/img/word_card_img/sing.jpg",
      audio: "./src/audio/word_card_audio/sing.mp3",
    },
    {
      word: "skip",
      translation: "пропускать, прыгать",
      imageSrc: "./src/img/word_card_img/skip.jpg",
      audio: "./src/audio/word_card_audio/skip.mp3",
    },
    {
      word: "swim",
      translation: "плавать",
      imageSrc: "./src/img/word_card_img/swim.jpg",
      audio: "./src/audio/word_card_audio/swim.mp3",
    },
  ],
  [
    {
      word: "cat",
      translation: "кот",
      imageSrc: "./src/img/word_card_img/cat.jpg",
      audio: "./src/audio/word_card_audio/cat.mp3",
    },
    {
      word: "chick",
      translation: "цыплёнок",
      imageSrc: "./src/img/word_card_img/chick.jpg",
      audio: "./src/audio/word_card_audio/chick.mp3",
    },
    {
      word: "chicken",
      translation: "курица",
      imageSrc: "./src/img/word_card_img/chicken.jpg",
      audio: "./src/audio/word_card_audio/chicken.mp3",
    },
    {
      word: "dog",
      translation: "собака",
      imageSrc: "./src/img/word_card_img/dog.jpg",
      audio: "./src/audio/word_card_audio/dog.mp3",
    },
    {
      word: "horse",
      translation: "лошадь",
      imageSrc: "./src/img/word_card_img/horse.jpg",
      audio: "./src/audio/word_card_audio/horse.mp3",
    },
    {
      word: "pig",
      translation: "свинья",
      imageSrc: "./src/img/word_card_img/pig.jpg",
      audio: "./src/audio/word_card_audio/pig.mp3",
    },
    {
      word: "rabbit",
      translation: "кролик",
      imageSrc: "./src/img/word_card_img/rabbit.jpg",
      audio: "./src/audio/word_card_audio/rabbit.mp3",
    },
    {
      word: "sheep",
      translation: "овца",
      imageSrc: "./src/img/word_card_img/sheep.jpg",
      audio: "./src/audio/word_card_audio/sheep.mp3",
    },
  ],
  [
    {
      word: "bird",
      translation: "птица",
      imageSrc: "./src/img/word_card_img/bird.jpg",
      audio: "./src/audio/word_card_audio/bird.mp3",
    },
    {
      word: "fish",
      translation: "рыба",
      imageSrc: "./src/img/word_card_img/fish1.jpg",
      audio: "./src/audio/word_card_audio/fish.mp3",
    },
    {
      word: "frog",
      translation: "жаба",
      imageSrc: "./src/img/word_card_img/frog.jpg",
      audio: "./src/audio/word_card_audio/frog.mp3",
    },
    {
      word: "giraffe",
      translation: "жираф",
      imageSrc: "./src/img/word_card_img/giraffe.jpg",
      audio: "./src/audio/word_card_audio/giraffe.mp3",
    },
    {
      word: "lion",
      translation: "лев",
      imageSrc: "./src/img/word_card_img/lion.jpg",
      audio: "./src/audio/word_card_audio/lion.mp3",
    },
    {
      word: "mouse",
      translation: "мышь",
      imageSrc: "./src/img/word_card_img/mouse.jpg",
      audio: "./src/audio/word_card_audio/mouse.mp3",
    },
    {
      word: "turtle",
      translation: "черепаха",
      imageSrc: "./src/img/word_card_img/turtle.jpg",
      audio: "./src/audio/word_card_audio/turtle.mp3",
    },
    {
      word: "dolphin",
      translation: "дельфин",
      imageSrc: "./src/img/word_card_img/dolphin.jpg",
      audio: "./src/audio/word_card_audio/dolphin.mp3",
    },
  ],
  [
    {
      word: "skirt",
      translation: "юбка",
      imageSrc: "./src/img/word_card_img/skirt.jpg",
      audio: "./src/audio/word_card_audio/skirt.mp3",
    },
    {
      word: "pants",
      translation: "брюки",
      imageSrc: "./src/img/word_card_img/pants.jpg",
      audio: "./src/audio/word_card_audio/pants.mp3",
    },
    {
      word: "blouse",
      translation: "блузка",
      imageSrc: "./src/img/word_card_img/blouse.jpg",
      audio: "./src/audio/word_card_audio/blouse.mp3",
    },
    {
      word: "dress",
      translation: "платье",
      imageSrc: "./src/img/word_card_img/dress.jpg",
      audio: "./src/audio/word_card_audio/dress.mp3",
    },
    {
      word: "boot",
      translation: "ботинок",
      imageSrc: "./src/img/word_card_img/boot.jpg",
      audio: "./src/audio/word_card_audio/boot.mp3",
    },
    {
      word: "shirt",
      translation: "рубашка",
      imageSrc: "./src/img/word_card_img/shirt.jpg",
      audio: "./src/audio/word_card_audio/shirt.mp3",
    },
    {
      word: "coat",
      translation: "пальто",
      imageSrc: "./src/img/word_card_img/coat.jpg",
      audio: "./src/audio/word_card_audio/coat.mp3",
    },
    {
      word: "shoe",
      translation: "туфли",
      imageSrc: "./src/img/word_card_img/shoe.jpg",
      audio: "./src/audio/word_card_audio/shoe.mp3",
    },
  ],
  [
    {
      word: "sad",
      translation: "грустный",
      imageSrc: "./src/img/word_card_img/sad.jpg",
      audio: "./src/audio/word_card_audio/sad.mp3",
    },
    {
      word: "angry",
      translation: "сердитый",
      imageSrc: "./src/img/word_card_img/angry.jpg",
      audio: "./src/audio/word_card_audio/angry.mp3",
    },
    {
      word: "happy",
      translation: "счастливый",
      imageSrc: "./src/img/word_card_img/happy.jpg",
      audio: "./src/audio/word_card_audio/happy.mp3",
    },
    {
      word: "tired",
      translation: "уставший",
      imageSrc: "./src/img/word_card_img/tired.jpg",
      audio: "./src/audio/word_card_audio/tired.mp3",
    },
    {
      word: "surprised",
      translation: "удивлённый",
      imageSrc: "./src/img/word_card_img/surprised.jpg",
      audio: "./src/audio/word_card_audio/surprised.mp3",
    },
    {
      word: "scared",
      translation: "испуганный",
      imageSrc: "./src/img/word_card_img/scared.jpg",
      audio: "./src/audio/word_card_audio/scared.mp3",
    },
    {
      word: "smile",
      translation: "улыбка",
      imageSrc: "./src/img/word_card_img/smile.jpg",
      audio: "./src/audio/word_card_audio/smile.mp3",
    },
    {
      word: "laugh",
      translation: "смех",
      imageSrc: "./src/img/word_card_img/laugh.jpg",
      audio: "./src/audio/word_card_audio/laugh.mp3",
    },
  ],
  [
    {
      word: "bread",
      translation: "хлеб",
      imageSrc: "./src/img/word_card_img/bread.jpg",
      audio: "./src/audio/word_card_audio/bread.mp3",
    },
    {
      word: "corn",
      translation: "кукуруза",
      imageSrc: "./src/img/word_card_img/corn.jpg",
      audio: "./src/audio/word_card_audio/corn.mp3",
    },
    {
      word: "garlic",
      translation: "чеснок",
      imageSrc: "./src/img/word_card_img/garlic.jpg",
      audio: "./src/audio/word_card_audio/garlic.mp3",
    },
    {
      word: "jam",
      translation: "варенье, джем",
      imageSrc: "./src/img/word_card_img/jam.jpg",
      audio: "./src/audio/word_card_audio/jam.mp3",
    },
    {
      word: "onion",
      translation: "лук",
      imageSrc: "./src/img/word_card_img/onion.jpg",
      audio: "./src/audio/word_card_audio/onion.mp3",
    },
    {
      word: "pepper",
      translation: "перец",
      imageSrc: "./src/img/word_card_img/pepper.jpg",
      audio: "./src/audio/word_card_audio/pepper.mp3",
    },
    {
      word: "plum",
      translation: "слива",
      imageSrc: "./src/img/word_card_img/plum.jpg",
      audio: "./src/audio/word_card_audio/plum.mp3",
    },
    {
      word: "walnut",
      translation: "грецкий орех",
      imageSrc: "./src/img/word_card_img/walnut.jpg",
      audio: "./src/audio/word_card_audio/walnut.mp3",
    },
  ],
  [
    {
      word: "bed",
      translation: "кровать",
      imageSrc: "./src/img/word_card_img/bed.jpg",
      audio: "./src/audio/word_card_audio/bed.mp3",
    },
    {
      word: "chair",
      translation: "стул",
      imageSrc: "./src/img/word_card_img/chair.jpg",
      audio: "./src/audio/word_card_audio/chair.mp3",
    },
    {
      word: "cup",
      translation: "кружка",
      imageSrc: "./src/img/word_card_img/cup.jpg",
      audio: "./src/audio/word_card_audio/cup.mp3",
    },
    {
      word: "cutlery",
      translation: "столовые приборы",
      imageSrc: "./src/img/word_card_img/cutlery.jpg",
      audio: "./src/audio/word_card_audio/cutlery.mp3",
    },
    {
      word: "pillow",
      translation: "подушка",
      imageSrc: "./src/img/word_card_img/pillow.jpg",
      audio: "./src/audio/word_card_audio/pillow.mp3",
    },
    {
      word: "shelf",
      translation: "полка",
      imageSrc: "./src/img/word_card_img/shelf.jpg",
      audio: "./src/audio/word_card_audio/shelf.mp3",
    },
    {
      word: "towel",
      translation: "полотенце",
      imageSrc: "./src/img/word_card_img/towel.jpg",
      audio: "./src/audio/word_card_audio/towel.mp3",
    },
    {
      word: "window",
      translation: "окно",
      imageSrc: "./src/img/word_card_img/window.jpg",
      audio: "./src/audio/word_card_audio/window.mp3",
    },
  ]
];

export { categories, words };
